### PR TITLE
Add dependabot configuration

### PR DESCRIPTION
**Pull request by jwillemsen**
* .github/dependabot.yml:
      Added.

### CODE REVIEW

**Comment by rnc** [comment]
Thanks!

**Comment by jwillemsen** [comment]
Maybe you have to manually enable dependabot for this project, see https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Comment by rnc** [comment]
> Maybe you have to manually enable dependabot for this project, see [github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)

@jwillemsen It seems to be running anyway. I'm not a massive fan of it to be honest ; creates an awful lot of noise for a constant stream of upgrades.

**Comment by rnc** [comment]
@jwillemsen I'm reverting this - it causes too many issues with non-backwards compatible changes with too much noise.

**Comment by jwillemsen** [comment]
Not a problem, you could use depandabot to keep the github action up to date

**Comment by jwillemsen** [comment]
See https://github.com/RemedyIT/axcioma/blob/master/.github/dependabot.yml for an example just for github actions

**Pull request merged**
