### PR TITLE
Fix links and add sloppy_names for IDL plugin upgrade

### PR DESCRIPTION
**Pull request by rnc**

### CODE REVIEW

**Comment by jwillemsen** [comment]
You could use a schedule to run your action weekly even when there are no changes and a `workflow_dispatch` so that you can start the action also manually, see https://github.com/RemedyIT/axcioma/blob/03692f37e17b33cd72088d15ac2d9f720472c627/.github/workflows/linux.yml#L14 for an example

**Comment by rnc** [comment]
> You could use a schedule to run your action weekly even when there are no changes and a `workflow_dispatch` so that you can start the action also manually, see [RemedyIT/axcioma@`03692f3`/.github/workflows/linux.yml#L14](https://github.com/RemedyIT/axcioma/blob/03692f37e17b33cd72088d15ac2d9f720472c627/.github/workflows/linux.yml#L14) for an example

@jwillemsen That doesn't avoid the problem that its giving broken updates (See the spring revert changes above). Security changes only would be ok but they can only be configured by the UI not in the config file currently in the v2 schema I believe. Therefore its seems more trouble than its worth.

**Comment by jwillemsen** [comment]
> @jwillemsen That doesn't avoid the problem that its giving broken updates (See the spring revert changes). Security changes only would be ok but they can only be configured by the UI not in the config file currently in the v2 schema I believe. Therefore its seems more trouble than its worth.

The schedule/workflow_dispatch isn't related to updates, schedule runs your action on a crontab so that it also runs for example weekly without any changes, that way when something on github action changes you know at least the action works, and the workflow_dispatch enabled you to manually run the action independent of a PR

**Comment by rnc** [comment]
> > @jwillemsen That doesn't avoid the problem that its giving broken updates (See the spring revert changes). Security changes only would be ok but they can only be configured by the UI not in the config file currently in the v2 schema I believe. Therefore its seems more trouble than its worth.
> 
> The schedule/workflow_dispatch isn't related to updates, schedule runs your action on a crontab so that it also runs for example weekly without any changes, that way when something on github action changes you know at least the action works, and the workflow_dispatch enabled you to manually run the action independent of a PR

Sorry I thought you were referring to the dependabot removal. The GH action has been configured to run on PR and deploy on snapshot ; that configuration I have used successfully in e.g. https://github.com/release-engineering/pom-manipulation-ext

**Comment by jwillemsen** [comment]
Ok, good to hear that it works. We did have cases where github changes something on their runners which broke our action, the schedule is now helpful to at least detect that in a quiet development period.

**Pull request merged**
